config/routes.rb
Rails.application.routes.draw do
  get 'jobs/index'

  get '/signup', to: 'users#get_signup', as: :render_signup
  post '/signup', to: 'users#do_signup', as: :signup

  root to: 'users#get_login'
  get '/login', to: 'users#get_login', as: :render_login
  post '/login', to: 'users#do_login', as: :login

  get '/logout', to: 'users#do_logout', as: :logout


  resources :shootings, only: [:index, :show, :create, :update, :destroy]
  post '/shootings/:shooting_id/get_week', to: 'shootings#get_week', as: :get_week

  post '/shootings/:shooting_id/create_employee', to: 'shootings#create_employee', as: :create_employee
  patch '/shootings/:shooting_id/update_employee/:employee_id', to: 'shootings#update_employee', as: :update_employee
  post '/shootings/:shooting_id/delete_employee/:employee_id', to: 'shootings#delete_employee', as: :delete_employee
  post '/shootings/:shooting_id/employee_contract_end/:employee_id', to: 'shootings#employee_contract_end', as: :employee_contract_end

  post '/shootings/:shooting_id/create_indemnity', to: 'shootings#create_indemnity', as: :create_indemnity
  patch '/shootings/:shooting_id/update_indemnity/:indemnity_id', to: 'shootings#update_indemnity', as: :update_indemnity
  post '/shootings/:shooting_id/delete_indemnity/:indemnity_id', to: 'shootings#delete_indemnity', as: :delete_indemnity

  resources :weeks, only: [:show, :create]
  post '/weeks/:week_id/employee_selection', to: 'weeks#employee_selection', as: :employee_selection
  post '/weeks/:week_id/update_day', to: 'weeks#update_day', as: :update_day
  post '/weeks/:week_id/create_day', to: 'weeks#create_day', as: :create_day
  post '/weeks/:week_id/delete_day', to: 'weeks#delete_day', as: :delete_day
  post '/weeks/:week_id/add_lunch', to: 'weeks#add_lunch', as: :add_lunch
  post '/weeks/:week_id/update_lunch', to: 'weeks#update_lunch', as: :update_lunch
  post '/weeks/:week_id/remove_lunch', to: 'weeks#remove_lunch', as: :remove_lunch
  post '/weeks/:week_id/get_shooting_hours', to: 'weeks#get_shooting_hours', as: :get_shooting_hours
  post '/weeks/:week_id/update_shooting_hours', to: 'weeks#update_shooting_hours', as: :update_shooting_hours

  resources :jobs, only: [:index, :create, :update, :destroy]
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :job, optional: false
  has_many :days, dependent: :destroy
  has_many :hours, through: :days
  belongs_to :shooting, optional: false

  validates_presence_of :name

  def week_hours(week_date)
    tot_week_hours = 0
    0.upto(6) do |i|
      day = days.where(date: week_date + i.days).take
      tot_week_hours += day.hours_number
    end
    tot_week_hours
  end

  def week_equiv_hours(week_date)
    tot_week_hours = week_hours(week_date)
    tot_week_hours - job.equiv_diff
  end

  def calculate_week_salary(week_date)
    hour_salary = job.salary_per_hour

    equiv_hours = week_equiv_hours(week_date)
    salary = 0
    0.upto(6) do |i|
      day = days.where(date: week_date + i.days).take

      day.hours.each do |h|
        salary += h.final_maj_rate*hour_salary
        equiv_hours -= 1
        break if (equiv_hours == 0)
      end

      break if (equiv_hours == 0)
    end
    salary
  end


  def ended_contract?
    !contract_end.nil?
  end
end

app/views/employees/_delete_modal_form.html.erb
<div class="modal-content">
  <div class="modal-header">
    <h4 class="modal-title">Supprimer Salarié</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">×</span>
    </button>
  </div>
  <div class="modal-body">
    <div class="row">
      <div class="col-sm-12">
        <h3><%= "#{employee.name} (#{employee.job.name})" %> : Etes-vous sûr(e) de vouloir supprimer ce salarié ?</h3>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <%= button_to 'Supprimer', delete_employee_path(shooting_id: shooting.id, employee_id: employee.id), class: 'btn btn-danger pull-right' %>
  </div>
</div>
<!-- /.modal-content -->

app/views/employees/_employee.html.erb
<% unless employee.id.nil? %>
    <tr>
      <td>
        <%= employee.name %>
      </td>
      <td>
        <%= employee.job.name %>
      </td>
      <td>
        <%= employee.contract_start.strftime('%d/%m/%Y') unless employee.contract_start.nil? %>
      </td>
      <td>
        <% unless employee.contract_end.nil? %>
            <%= employee.contract_end.strftime('%d/%m/%Y') %>
        <% else %>
            <%= button_to 'Fin de contrat', employee_contract_end_path(shooting_id: @shooting.id, employee_id: employee.id), class: 'btn-sm btn-primary' %>
        <% end %>
      </td>
      <td>
        <button id="update-employee-<%= employee.id %>-modal" class="btn-sm btn-primary">Modifier</button>
      </td>
      <td>
        <button id="delete-employee-<%= employee.id %>-modal" class="btn-sm btn-danger">x</button>
      </td>
    </tr>

    <script>
      $(document).on('click', '#update-employee-<%= employee.id %>-modal', function() {
          var modal = $('div.modal#update_employee_modal');
          var modal_body = modal.find('div.modal-dialog');
          var update_modal_form = '<%= raw "#{ render 'employees/update_modal_form', {employee: employee, shooting: @shooting} }".gsub("\n", '') %>';

          modal_body.children().remove();
          $(update_modal_form).appendTo(modal_body);

          var datepickers = modal.modal().find('input.datepicker');
          datepickers.each(function() {
              var value = $(this).val();
              if (value !== '') {
                  value = value.split('-').reverse().join('/');
                  $(this).val(value);
              }
              $(this).datepicker({
                  dateFormat: 'dd/mm/yy'
              });
          });
      });

      $(document).on('click', '#delete-employee-<%= employee.id %>-modal', function() {
          var modal_body = $('div.modal#delete_employee_modal div.modal-dialog');
          var delete_modal_form = '<%= raw "#{ render 'employees/delete_modal_form', {employee: employee, shooting: @shooting} }".gsub("\n", '') %>';

          modal_body.children().remove();
          $(delete_modal_form).appendTo(modal_body);
          $('div.modal#delete_employee_modal').modal();
      });
    </script>
<% end %>

app/views/employees/_update_modal_form.html.erb
<%=form_for employee, url: update_employee_path(shooting_id: shooting.id, employee_id: employee.id) do |e|%>
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Mise à jour Salarié</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-sm-12">
            <div class="form-group">
              <%=e.label 'Nom'%>
              <%=e.text_field :name, class:'form-control' %>
            </div>
          </div>
          <div class="col-sm-12">
            <div class="form-group">
              <%=e.label 'Job'%>
              <%=e.select :job_id, Job.all.collect {|j| [j.name, j.id]}, class:'form-control' %>
            </div>
          </div>
          <div class="col-sm-12">
            <div class="form-group">
              <%=e.label 'Début de contrat'%>
              <%=e.text_field :contract_start, class:'form-control datepicker' %>
            </div>
          </div>
          <div class="col-sm-12">
            <div class="form-group">
              <%=e.label 'Fin de contrat'%>
              <%=e.text_field :contract_end, class:'form-control datepicker' %>
            </div>
          </div>
          <div class="col-sm-12">
            <div class="form-group">
              <%=e.label 'Contrat à la journée ?'%>
              <%=e.check_box :daily_contract, class:'form-control' %>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <input type="submit" class="pull-right btn btn-success" value="Enregistrer">
      </div>
    </div>
    <!-- /.modal-content -->
<% end %>
</div>
<!-- /.modal-dialog -->