config/routes.rb
Rails.application.routes.draw do
  get 'jobs/index'

  get '/signup', to: 'users#get_signup', as: :render_signup
  post '/signup', to: 'users#do_signup', as: :signup

  root to: 'users#get_login'
  get '/login', to: 'users#get_login', as: :render_login
  post '/login', to: 'users#do_login', as: :login

  get '/logout', to: 'users#do_logout', as: :logout


  resources :shootings, only: [:index, :show, :create, :update, :destroy]
  post '/shootings/:shooting_id/get_week', to: 'shootings#get_week', as: :get_week

  post '/shootings/:shooting_id/create_employee', to: 'shootings#create_employee', as: :create_employee
  patch '/shootings/:shooting_id/update_employee/:employee_id', to: 'shootings#update_employee', as: :update_employee
  post '/shootings/:shooting_id/delete_employee/:employee_id', to: 'shootings#delete_employee', as: :delete_employee
  post '/shootings/:shooting_id/employee_contract_end/:employee_id', to: 'shootings#employee_contract_end', as: :employee_contract_end

  post '/shootings/:shooting_id/create_indemnity', to: 'shootings#create_indemnity', as: :create_indemnity
  patch '/shootings/:shooting_id/update_indemnity/:indemnity_id', to: 'shootings#update_indemnity', as: :update_indemnity
  post '/shootings/:shooting_id/delete_indemnity/:indemnity_id', to: 'shootings#delete_indemnity', as: :delete_indemnity

  resources :weeks, only: [:show, :create]
  post '/weeks/:week_id/employee_selection', to: 'weeks#employee_selection', as: :employee_selection
  post '/weeks/:week_id/update_day', to: 'weeks#update_day', as: :update_day
  post '/weeks/:week_id/create_day', to: 'weeks#create_day', as: :create_day
  post '/weeks/:week_id/delete_day', to: 'weeks#delete_day', as: :delete_day
  post '/weeks/:week_id/add_lunch', to: 'weeks#add_lunch', as: :add_lunch
  post '/weeks/:week_id/update_lunch', to: 'weeks#update_lunch', as: :update_lunch
  post '/weeks/:week_id/remove_lunch', to: 'weeks#remove_lunch', as: :remove_lunch
  post '/weeks/:week_id/get_shooting_hours', to: 'weeks#get_shooting_hours', as: :get_shooting_hours
  post '/weeks/:week_id/update_shooting_hours', to: 'weeks#update_shooting_hours', as: :update_shooting_hours

  resources :jobs, only: [:index, :create, :update, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :shootings

  has_secure_password

  validates :email, uniqueness: true
  validate :email_must_be_valid


  def self.login email, password
    user = User.find_by_email email
    if user
      if user.authenticate password
        return user
      else
        raise ArgumentError, 'Erreur lors du login'
      end
    else
      raise ArgumentError, 'Erreur lors du login'
    end
  end

  def self.validate_email email
    email =~ /\A[^@\s]+@[^@\s]+\z/ ? true : false
  end

  def email_must_be_valid
    errors.add('Format d\'email non valide') unless User.validate_email(email)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_if_session, only:[:get_login, :get_signup, :do_login, :do_signup]

  before_action :check_for_user_session, except:[:get_login, :get_signup, :do_signup, :do_login, :do_logout]

  def data
    # Maybe change the name of this action
    # Manage the jobs and all that kind of constant stuff
    @jobs = Job.all
  end

  def get_signup
    @user = User.new
    render :signup, layout: 'garden'
  end

  def do_signup
    begin
      user = User.new(user_params)
      if user.save
        log_in user
        redirect_to shootings_path, flash:{ success: 'Enregistrement réussi'}
      else
        raise ArgumentError, user.errors.full_messages.join(' ; ')
      end
    rescue Exception => e
      redirect_to :render_signup, flash:{ danger: e.message }
    end
  end

  def get_login
    render :login, layout: 'garden'
  end

  def do_login
    begin
      user = User.login params[:user][:email], params[:user][:password]
      log_in user
      redirect_to shootings_path
    rescue Exception => e
      redirect_to :render_login, flash:{ danger: (e.message)}
    end
  end

  def do_logout
    log_out
    redirect_to :root, flash: {success: 'Déconnexion réussie'}
  end


  private

  def redirect_if_session
    if session[:user_id]
      redirect_to shootings_path
    end
  end

  def user_params
    params.require(:user).permit(:email,
                                 :password,
                                 :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/login.html.erb
<div class="row justify-content-center">
  <div class="col-md-8">
    <div class="card-group mb-0">
      <div class="card p-2">
        <div class="card-block">
          <%=form_for :user, url: login_path do |f|%>
              <h1>Login</h1>
              <p class="text-muted">Connexion</p>
              <div class="input-group mb-1">
                        <span class="input-group-addon">
                            <i class="icon-envelope"></i>
                        </span>
                <%= f.email_field :email, class: 'form-control', placeholder: 'Email' %>
              </div>
              <div class="input-group mb-2">
                        <span class="input-group-addon">
                            <i class="icon-lock"></i>
                        </span>
                <%= f.password_field :password, class: 'form-control', placeholder: 'Mot de passe' %>
              </div>
              <div class="row">
                <div class="col-6">
                  <%= f.submit 'Login', class: 'btn btn-primary px-2' %>
                </div>
              </div>
          <%end%>
        </div>
      </div>
      <div class="card card-inverse card-primary py-3 hidden-md-down" style="width:44%">
        <div class="card-block text-center">
          <div>
            <h2>S'enregistrer</h2>
            <p>Rapidement</p>
            <a href="<%= render_signup_path %>" class="btn btn-primary active mt-1">S'enregistrer maintenant</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/signup.html.erb
<div class="row justify-content-center">
  <div class="col-md-6">
    <div class="card mx-2">
      <div class="card-block p-2">
        <%=form_for @user, url: :signup do |f|%>
            <h1>S'enregistrer</h1>
            <p class="text-muted">Créez votre compte</p>
            <div class="input-group mb-1">
              <span class="input-group-addon">@</span>
              <%= f.email_field :email, class: 'form-control', placeholder: 'Email' %>
            </div>
            <div class="input-group mb-1">
                    <span class="input-group-addon">
                        <i class="icon-lock"></i>
                    </span>
              <%= f.password_field :password, class: 'form-control', placeholder: 'Mot de passe' %>
            </div>

            <div class="input-group mb-2">
                    <span class="input-group-addon">
                        <i class="icon-lock"></i>
                    </span>
              <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'Confirmation' %>
            </div>

            <%= f.submit 'Créer compte', class: 'btn btn-block btn-success' %>
        <%end%>
      </div>
    </div>
  </div>
</div>