config/routes.rb
Rails.application.routes.draw do
  get 'jobs/index'

  get '/signup', to: 'users#get_signup', as: :render_signup
  post '/signup', to: 'users#do_signup', as: :signup

  root to: 'users#get_login'
  get '/login', to: 'users#get_login', as: :render_login
  post '/login', to: 'users#do_login', as: :login

  get '/logout', to: 'users#do_logout', as: :logout


  resources :shootings, only: [:index, :show, :create, :update, :destroy]
  post '/shootings/:shooting_id/get_week', to: 'shootings#get_week', as: :get_week

  post '/shootings/:shooting_id/create_employee', to: 'shootings#create_employee', as: :create_employee
  patch '/shootings/:shooting_id/update_employee/:employee_id', to: 'shootings#update_employee', as: :update_employee
  post '/shootings/:shooting_id/delete_employee/:employee_id', to: 'shootings#delete_employee', as: :delete_employee
  post '/shootings/:shooting_id/employee_contract_end/:employee_id', to: 'shootings#employee_contract_end', as: :employee_contract_end

  post '/shootings/:shooting_id/create_indemnity', to: 'shootings#create_indemnity', as: :create_indemnity
  patch '/shootings/:shooting_id/update_indemnity/:indemnity_id', to: 'shootings#update_indemnity', as: :update_indemnity
  post '/shootings/:shooting_id/delete_indemnity/:indemnity_id', to: 'shootings#delete_indemnity', as: :delete_indemnity

  resources :weeks, only: [:show, :create]
  post '/weeks/:week_id/employee_selection', to: 'weeks#employee_selection', as: :employee_selection
  post '/weeks/:week_id/update_day', to: 'weeks#update_day', as: :update_day
  post '/weeks/:week_id/create_day', to: 'weeks#create_day', as: :create_day
  post '/weeks/:week_id/delete_day', to: 'weeks#delete_day', as: :delete_day
  post '/weeks/:week_id/add_lunch', to: 'weeks#add_lunch', as: :add_lunch
  post '/weeks/:week_id/update_lunch', to: 'weeks#update_lunch', as: :update_lunch
  post '/weeks/:week_id/remove_lunch', to: 'weeks#remove_lunch', as: :remove_lunch
  post '/weeks/:week_id/get_shooting_hours', to: 'weeks#get_shooting_hours', as: :get_shooting_hours
  post '/weeks/:week_id/update_shooting_hours', to: 'weeks#update_shooting_hours', as: :update_shooting_hours

  resources :jobs, only: [:index, :create, :update, :destroy]
end

app/models/shooting.rb
class Shooting < ApplicationRecord
  has_many :weeks, dependent: :destroy
  has_many :days, through: :weeks
  has_many :hours, through: :days
  has_many :employees, dependent: :destroy

  has_many :indemnities, dependent: :destroy

  belongs_to :user, optional: false

  validates_presence_of :name

  def number_of_weeks
    weeks.nil? ? 0 : weeks.count
  end
end

app/controllers/shootings_controller.rb
class ShootingsController < ApplicationController
  before_action :check_for_user_session

  def index
    @shootings = current_user.shootings
    @current_shooting = @shootings.nil? ? nil : @shootings.order(updated_at: :desc).first
    @new_shooting = current_user.shootings.new
    # All your shootings (archive page also later ?) with number of weeks etc
    # Create a new shooting from here
  end

  def show
    # All the employees, manage the contracts from here
    # See also the weeks
    # Maybe split the two in two pages
    @shooting = current_user.shootings.find(params[:id])
    session[:shooting_id] = @shooting.id
    @employees = @shooting.employees
    @indemnities = @shooting.indemnities
    @last_weeks = @shooting.weeks.order(beginning_date: :desc).take(4)
    @new_week = @shooting.weeks.new
    @new_employee = @shooting.employees.new
    @new_indemnity = @shooting.indemnities.new
  end

  def get_week
    shooting = current_user.shootings.find(params[:shooting_id])
    beginning_date = Date.strptime(params[:date], "%d/%m/%Y").beginning_of_week
    week = shooting.weeks.find_by(beginning_date: beginning_date)
    return redirect_to shooting, flash:{ danger: "Cette semaine n'existe pas" } if week.nil?
    redirect_to week
  end

  def create_employee
    shooting = current_user.shootings.find(params[:shooting_id])

    contract_start = params[:employee][:contract_start].empty? ? nil : Date.strptime(params[:employee][:contract_start], '%d/%m/%Y')
    contract_end = params[:employee][:contract_end].empty? ? nil : Date.strptime(params[:employee][:contract_end], '%d/%m/%Y')

    employee = shooting.employees.new(name: params[:employee][:name],
                                      job_id: params[:employee][:job_id],
                                      contract_start: contract_start,
                                      contract_end: contract_end,
                                      daily_contract: params[:employee][:daily_contract])

    if employee.save
      redirect_to shooting, flash: { success: 'Salarié ajouté' }
    else
      redirect_to shooting, flash: { danger: "Echec de l'ajout du salarié" }
    end
  end

  def update_employee
    shooting = current_user.shootings.find(params[:shooting_id])
    employee = shooting.employees.find(params[:employee_id])

    contract_start = params[:employee][:contract_start].empty? ? nil : Date.strptime(params[:employee][:contract_start], '%d/%m/%Y')
    contract_end = params[:employee][:contract_end].empty? ? nil : Date.strptime(params[:employee][:contract_end], '%d/%m/%Y')

    employee.update_attributes(name: params[:employee][:name],
                               job_id: params[:employee][:job_id],
                               contract_start: contract_start,
                               contract_end: contract_end,
                               daily_contract: params[:employee][:daily_contract])

    if employee.save
      redirect_to shooting, flash: { success: 'Salarié mis à jour' }
    else
      redirect_to shooting, flash: { danger: "Echec de la mise à jour du salarié" }
    end
  end

  def delete_employee
    shooting = current_user.shootings.find(params[:shooting_id])
    employee = shooting.employees.find(params[:employee_id]).destroy

    if employee.destroyed?
      redirect_to shooting, flash: { success: 'Salarié mis à jour' }
    else
      redirect_to shooting, flash: { danger: "Echec de la mise à jour du salarié" }
    end
  end

  def employee_contract_end
    shooting = current_user.shootings.find(params[:shooting_id])
    employee = shooting.employees.find(params[:employee_id])
    employee.update_attribute(:contract_end, Date.today)

    redirect_to shooting, flash: { success: 'Fin du contrat ajoutée pour ' + employee.name }
  end

  def create_indemnity
    shooting = current_user.shootings.find(params[:shooting_id])

    indemnity = shooting.indemnities.new(name: params[:indemnity][:name],
                                         value: params[:indemnity][:value])

    if indemnity.save
      redirect_to shooting, flash: { success: 'Indemnité ajoutée' }
    else
      redirect_to shooting, flash: { danger: "Echec de l'ajout de l'indemnité" }
    end
  end

  def update_indemnity
    shooting = current_user.shootings.find(params[:shooting_id])
    indemnity = shooting.indemnities.find(params[:indemnity_id])

    indemnity.update_attributes(name: params[:indemnity][:name],
                                value: params[:indemnity][:value])

    if indemnity.save
      redirect_to shooting, flash: { success: 'Indemnité mise à jour' }
    else
      redirect_to shooting, flash: { danger: "Echec de la mise à jour de l'indemnité" }
    end
  end

  def delete_indemnity
    shooting = current_user.shootings.find(params[:shooting_id])
    indemnity = shooting.indemnities.find(params[:indemnity_id]).destroy

    if indemnity.destroyed?
      redirect_to shooting, flash: { success: 'Indemnité supprimée' }
    else
      redirect_to shooting, flash: { danger: "Echec de la suppression de l'indemnité" }
    end
  end

  def create
    shooting = current_user.shootings.new(name: params[:shooting][:name], start: params[:shooting][:start])
    if shooting.save
      redirect_to shooting, flash:{ success: 'Tournage créé' }
    else
      redirect_to shootings_path, flash:{ danger: 'Echec de la création du tournage' }
    end
  end

  def update
    shooting = current_user.shootings.find(params[:id])
    if shooting.update_attribute(:name, params[:shooting][:name])
      redirect_to shooting, flash:{ success: 'Tournage mis à jour' }
    else
      redirect_to shootings_path, flash:{ danger: 'Echec de la mise à jour du tournage' }
    end
  end

  def destroy
    begin
      current_user.shootings.find(params[:id]).destroy
      redirect_to shootings_path, flash:{ success: 'Tournage supprimé' }
    rescue Exception => e
      redirect_to shootings_path, flash:{ danger: e.message }
    end
  end
end

app/helpers/shootings_helper.rb
module ShootingsHelper
end

app/views/shootings/_shooting.html.erb
<% unless shooting.id.nil? %>
  <tr>
    <td>
      <%= link_to shooting.name, shooting %>
    </td>
    <td>
      <%= shooting.number_of_weeks.to_s + ' semaines' %>
    </td>
    <td>
      <%= shooting.start.strftime('%d/%m/%Y') unless shooting.start.nil? %>
    </td>
    <td>
      <%= shooting.end.strftime('%d/%m/%Y') if !shooting.end.nil? && shooting.end < Date.today %>
    </td>
  </tr>
<% end %>

app/views/shootings/index.html.erb
<div class="row">
  <% unless @current_shooting.nil? %>
      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            <%= link_to @current_shooting.name, @current_shooting %>
          </div>
          <div class="card-block">
            <div class="row">
              <div class="col-md-8 px-2">
                Tournage actuel avec quelques stats et employés etc, principales infos
              </div>
              <div class="col-md-4 px-2">
                Vue rapide sur la semaine actuelle
              </div>
            </div>
          </div>
        </div>
        <!--/.card-->
      </div>
  <% end %>

  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        Tournages
        <a href="#" data-toggle="modal" data-target="#create_shooting_modal" class="btn btn-primary pull-right">Nouveau tournage</a>
      </div>
      <div class="card-block">
        <table class="table table-bordered table-striped table-condensed text-center" id="shootings">
          <thead>
          <tr>
            <th>Film</th>
            <th>Nombre de semaines</th>
            <th>Début du tournage</th>
            <th>Fin du tournage</th>
          </tr>
          </thead>
          <tbody>
          <%= render @shootings %>
          </tbody>
        </table>
      </div>
    </div>
    <!--/.card-->
  </div>
</div>

<div class="modal fade" id="create_shooting_modal" tabindex="-1" role="dialog" aria-labelledby="Create Shooting Modal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <%=form_for @new_shooting, url: :shootings do |s|%>
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title">Nouveau tournage</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">
            <div class="row">
              <div class="col-sm-12">
                <div class="form-group">
                  <%=s.label :nom%>
                  <%=s.text_field :name, class:'form-control' %>
                </div>
              </div>
              <div class="col-sm-12">
                <div class="form-group">
                  <%=s.label 'Début'%>
                  <%=s.text_field :start, class:'form-control datepicker' %>
                </div>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <input type="submit" class="pull-right btn btn-success" value="Enregistrer">
          </div>
        </div>
        <!-- /.modal-content -->
    <% end %>
  </div>
  <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<script>
    $( function() {
        $( "input.datepicker" ).datepicker({
            dateFormat: "dd/mm/yy",
            defaultDate: 0
        });
    } );
</script>

app/views/shootings/show.html.erb
<% # TODO: Intégrer weeks/show ? insérer le calendrier ici avec la possibilité de switcher de semaine ? Le controller weeks sert à rien %>
<% # TODO: Afficher des infos intéressantes avec les semaines : nombre d'employés sans fin de contrat sans heures de travail sur la semaine, nombre d'employés sous 35h etc %>

<h1 class="text-center">
  <%= @shooting.name %>
</h1>


<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        Calendrier
        <a href="#" data-toggle="modal" data-target="#create_week_modal" class="btn btn-primary pull-right">Ajouter semaine</a>
      </div>
      <div class="card-block">
        <div class="row">
          <div class="col-md-8 px-2">
            <%= link_to 'Semaine du ' + @last_weeks[0].beginning_date.strftime('%d/%m/%Y'), @last_weeks[0] if @last_weeks.length > 0 %>
          </div>
          <div class="col-md-4 px-2">
            <div class="row">
              <div class="col-md-12"><%= link_to 'Semaine du ' + @last_weeks[1].beginning_date.strftime('%d/%m/%Y'), @last_weeks[1] if @last_weeks.length > 1 %></div>
              <div class="col-md-12"><%= link_to 'Semaine du ' + @last_weeks[2].beginning_date.strftime('%d/%m/%Y'), @last_weeks[2] if @last_weeks.length > 2 %></div>
              <div class="col-md-12"><%= link_to 'Semaine du ' + @last_weeks[3].beginning_date.strftime('%d/%m/%Y'), @last_weeks[3] if @last_weeks.length > 3 %></div>
            </div>
          </div>
        </div>
      </div>
      <div class="card-footer">
        <div class="row">
          <div class="col-sm-3 offset-sm-6">
            <div class="form-group">
              <input type="text" name="week" class="form-control datepicker pull-right">
            </div>
          </div>
          <div class="col-sm-3">
            <div class="form-group">
              <button class="pull-right btn btn-success" id="get-week">Aller à la semaine</button>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!--/.card-->
  </div>

  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        Salariés
        <a href="#" data-toggle="modal" data-target="#create_employee_modal" class="btn btn-primary pull-right">Ajouter salarié</a>
      </div>
      <div class="card-block">
        <table class="table table-bordered table-striped table-condensed text-center" id="employees">
          <thead>
          <tr>
            <th>Nom</th>
            <th>Fonction</th>
            <th>Début de contrat</th>
            <th>Fin de contrat</th>
            <th>Mettre à jour</th>
            <th>Supprimer</th>
          </tr>
          </thead>
          <tbody>
          <%= render @employees %>
          </tbody>
        </table>
      </div>
    </div>
    <!--/.card-->
  </div>

  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        Indemnités
        <a href="#" data-toggle="modal" data-target="#create_indemnity_modal" class="btn btn-primary pull-right">Ajouter indemnité</a>
      </div>
      <div class="card-block">
        <table class="table table-bordered table-striped table-condensed text-center" id="indemnities">
          <thead>
          <tr>
            <th>Nom</th>
            <th>Valeur</th>
            <th>Mettre à jour</th>
            <th>Supprimer</th>
          </tr>
          </thead>
          <tbody>
          <%= render @indemnities %>
          </tbody>
        </table>
      </div>
    </div>
    <!--/.card-->
  </div>
</div>

<button class="btn btn-danger pull-right">Fin de tournage</button>

<div class="modal fade" id="create_week_modal" tabindex="-1" role="dialog" aria-labelledby="Create Week Modal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <%=form_for @new_week, url: :weeks do |s|%>
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title">Nouvelle semaine</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">
            <div class="row">
              <div class="col-sm-12">
                <div class="form-group">
                  <%=s.label 'Semaine du...'%>
                  <%=s.text_field :beginning_date, class:'form-control datepicker' %>
                </div>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <input type="submit" class="pull-right btn btn-success" value="Enregistrer">
          </div>
        </div>
        <!-- /.modal-content -->
    <% end %>
  </div>
  <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<div class="modal fade" id="create_employee_modal" tabindex="-1" role="dialog" aria-labelledby="Create Employee Modal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <%=form_for @new_employee, url: create_employee_path(shooting_id: @shooting.id) do |e|%>
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title">Nouveau Salarié</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">
            <div class="row">
              <div class="col-sm-12">
                <div class="form-group">
                  <%=e.label 'Nom'%>
                  <%=e.text_field :name, class:'form-control' %>
                </div>
              </div>
              <div class="col-sm-12">
                <div class="form-group">
                  <%=e.label 'Job'%>
                  <%=e.select :job_id, Job.all.collect {|j| [j.name, j.id]}, class:'form-control' %>
                </div>
              </div>
              <div class="col-sm-12">
                <div class="form-group">
                  <%=e.label 'Début de contrat'%>
                  <%=e.text_field :contract_start, class:'form-control datepicker' %>
                </div>
              </div>
              <div class="col-sm-12">
                <div class="form-group">
                  <%=e.label 'Fin de contrat'%>
                  <%=e.text_field :contract_end, class:'form-control datepicker' %>
                </div>
              </div>
              <div class="col-sm-12">
                <div class="form-group">
                  <%=e.label 'Contrat à la journée ?'%>
                  <%=e.check_box :daily_contract, class:'form-control' %>
                </div>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <input type="submit" class="pull-right btn btn-success" value="Enregistrer">
          </div>
        </div>
        <!-- /.modal-content -->
    <% end %>
  </div>
  <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<div class="modal fade" id="update_employee_modal" tabindex="-1" role="dialog" aria-labelledby="Update Employee Modal" aria-hidden="true">
  <div class="modal-dialog" role="document">
  </div>
  <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<div class="modal fade" id="delete_employee_modal" tabindex="-1" role="dialog" aria-labelledby="Delete Employee Modal" aria-hidden="true">
  <div class="modal-dialog" role="document">
  </div>
  <!-- /.modal-dialog -->
</div>
<!-- /.modal -->



<div class="modal fade" id="create_indemnity_modal" tabindex="-1" role="dialog" aria-labelledby="Create Indemnity Modal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <%=form_for @new_indemnity, url: create_indemnity_path(shooting_id: @shooting.id) do |i|%>
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title">Nouvelle Indemnité</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">
            <div class="row">
              <div class="col-sm-12">
                <div class="form-group">
                  <%=i.label 'Nom'%>
                  <%=i.text_field :name, class:'form-control' %>
                </div>
              </div>
              <div class="col-sm-12">
                <div class="form-group">
                  <%=i.label 'Valeur'%>
                  <%=i.number_field :value, class:'form-control', step: 0.01 %>
                </div>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <input type="submit" class="pull-right btn btn-success" value="Enregistrer">
          </div>
        </div>
        <!-- /.modal-content -->
    <% end %>
  </div>
  <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<div class="modal fade" id="update_indemnity_modal" tabindex="-1" role="dialog" aria-labelledby="Update Indemnity Modal" aria-hidden="true">
  <div class="modal-dialog" role="document">
  </div>
  <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<div class="modal fade" id="delete_indemnity_modal" tabindex="-1" role="dialog" aria-labelledby="Delete Indemnity Modal" aria-hidden="true">
  <div class="modal-dialog" role="document">
  </div>
  <!-- /.modal-dialog -->
</div>
<!-- /.modal -->


<script>
    $( function() {
        $( "input.datepicker" ).datepicker({
            dateFormat: "dd/mm/yy",
            defaultDate: 0
        });
    } );

    $('button#get-week').click(function() {
        var date = $('input[name="week"]').val();
        if (date == '') return;

        var params = {date: date};

        $.post('<%= get_week_path(shooting_id: @shooting.id) %>', params);
    });
</script>